### ISSUE TITLE
算术编码的取反位的设计

### ISSUE THREAD

**Issue by wang-zm18** [SincereXIA/ArithmeticCodingMFC#1]
您好，我想问一下ACC.cpp中算术编码的实现过程中为什么要对当前不确定位添加取反位的设计，而且bit_plus_follow函数中为什么需要添加和后续确定编码比特相反的值，而且添加的位置在后续确定编码比特之后？谢谢！

**Comment by SincereXIA** [comment]
具体可以看这篇论文：http://www.sachingarg.com/compression/entropy_coding/acm87_arithmetic_coding.pdf

**Comment by wang-zm18** [comment]
好的，多谢！

SincereXIA <notifications@github.com> 于2020年4月30日周四 下午11:04写道：
